### ISSUE TITLE
BE-1-post_Category

### ISSUE THREAD

**Issue by RicoMeinhof** [RicoMeinhof/sales-taxes#1]
### Description
**Create test and functionality for _adding categories_**
### TODO
**Tests**
- [ ] Create 
- [ ] when category is valid => receive status code "ok"
- [ ] when category is valid => save to database
- [ ] when category is valid => receive success message
- [ ] when category is null => receive status code "bad request"
- [ ] when category is empty => receive status code "bad request"
- [ ] when category is already existing => receive status code "bad request"
- [ ] when category is not only alphabetical => receive status code "bad request"
- [ ] when category is too long => receive status code "bad request"
- [ ] when category is too short => receive status code "bad request"

**Functionality**
- [ ] Create class Category (attr: id, name)
- [ ] Create category controller
- [ ] Create JPA repository for interactions with the database
- [ ] Create Service for business logic
- Implement the functionality to ensure the tests will succeed
- [ ] save the category, send success message
- [ ] add condition for: category is null
- [ ] add condition for: name is empty
- [ ] add condition for: name is not only alphabetical
- [ ] add condition for: name is too long
- [ ] add condition for: name is too short
