### ISSUE TITLE
BE-2-delete_Category

### ISSUE THREAD

**Issue by RicoMeinhof** [RicoMeinhof/sales-taxes#2]
### Description
**Create tests and functionality for _deleting categories_**
### TODO
**Tests**
- [ ] when category exists => receive status code "ok"
- [ ] when category exists => delete from database
- [ ] when category exists => receive success message
- [ ] when category not exists => receive status code "bad request"

**Functionality**

Implement the functionality to ensure the tests will succeed
- [ ] delete the category
- [ ] send success message
