### ISSUE TITLE
FE-1-Create_header_and_Shop_and_Category_pages

### ISSUE THREAD

**Issue by RicoMeinhof** [RicoMeinhof/sales-taxes#3]
### Description
**Create tests and functionality for _header_, _shop-page_ and category-page_**
### TODO
**Tests**
- [ ] Create Category Test file
- [ ] Create Shop Test file
- [ ] Create Header Test file
- [ ] Header has link elements for shop and categories
- [ ] Shop link leads to shop page
- [ ] Category link leads to category page

**Functionality**
- [ ] Create Category.vue file
- [ ] Create Shop.vue file
- [ ] Create Header.vue file
- [ ] Adjust App.vue
- [ ] Styling of header elements

Implement the functionality to ensure the tests will succeed
- [ ] Header has link elements for shop and categories
- [ ] Shop link leads to shop page
- [ ] Category link leads to category page
